name: Deploy Golang to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Jalankan Perintah di VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/project-golang
            git pull origin main
            # Build ulang binary terbarunya
            go build -o app-rizal main.go
            # Restart service biar binary baru yang jalan
            sudo systemctl restart golang-app
